### ISSUE TITLE
Bugs in OpenSSL docs causing install problem on RHEL7

### ISSUE THREAD

**Issue by captainpp** [Metaswitch/openssl#1]
I'm trying to build and install sprout on RHEL 7 (beta).  The installation of OpenSSL fails due to some formatting errors and typos in the OpenSSL docs.  For example:

cms.pod around line 457: Expected text after =item, not a number
cms.pod around line 461: Expected text after =item, not a number
cms.pod around line 465: Expected text after =item, not a number
cms.pod around line 470: Expected text after =item, not a number
cms.pod around line 474: Expected text after =item, not a number

OPENSSL_ia32cap.pod around line 23: '=item' outside of any '=over'
OPENSSL_ia32cap.pod around line 88: Unknown directive: =itme
OPENSSL_ia32cap.pod around line 23: =over without closing =back

SSL_accept.pod around line 53: Expected text after =item, not a number

(Same problem exists in SSL_clear.pod, SSL_COMP_add_compression_method.pod, SSL_connect.pod, SSL_CTX_add_session.pod, SSL_CTX_load_verify_locations.pod, SSL_CTX_set_client_CA_list.pod, SSL_CTX_set_session_id_context.pod, SSL_CTX_set_ssl_version.pod, SSL_do_handshake.pod, SSL_session_reused.pod, SSL_set_fd.pod, SSL_set_session.pod, SSL_shutdown.pod.)

http://lists.openembedded.org/pipermail/openembedded-core/2013-October/085343.html may help.

**Comment by rkd-msw** [comment]
Closing as stale (and almost certainly fixed by the above).
